### ISSUE TITLE
ViewerExample: Generate mesh normals logic is backwards

### ISSUE THREAD

**Issue by bz-next** [mosra/magnum-examples#109]
The code:

```
        if(meshData->hasAttribute(Trade::MeshAttribute::Normal))
            flags |= MeshTools::CompileFlag::GenerateFlatNormals;
```

seems backwards, as we'd only want to generate normals if none were present in the mesh data.

This would need to be fixed in the example webpage as well.

**Comment by mosra** [comment]
Lol, what a stupid mistake. Fixed in b12b1e348433883cf90fa348d3a661e1d4da9744, thanks!
