### ISSUE TITLE
Cubemap example not running

### ISSUE THREAD

**Issue by acterhd** [mosra/magnum-examples#28]
I trying next: 
- Install Ubuntu Mate (16.04) in PC
- Install all corrade, magnum, etc.. 
- Install examples (with cubemaps custom flag)
- Install plugins (I installed only jpeg and png at this moment)

Triangle example working. But I can't run cubemap example. 

```
acterhd@acterhd-desktop:~/magnum-examples/build$ sudo /usr/bin/magnum-cubemap
Renderer: GeForce GTX 970/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.5.0 NVIDIA 367.44
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_EXT_direct_state_access
    GL_EXT_texture_filter_anisotropic
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
Trade::AbstractImporter::openFile(): cannot open file +x.jpg
Trade::AbstractImporter::image2D(): no file opened
Aborted (core dumped)

```

**Comment by Squareys** [comment]
Hi @acterhd !

Are you running the example from within an IDE? In that case, please make sure the working directory of the application is `magnum-examples/src/cubemap/` :)

Regards, Squareys.

**Comment by acterhd** [comment]
Yes, I found binary in build/src/cubemap, but works only if move images to dirrctory. Not working after `make install` i.e. in installed directory.

**Comment by Squareys** [comment]
@mosra This sounds like the .jpeg files of the cupemap example are not installed into the right folder. The [CMakeLists.txt](https://github.com/mosra/magnum-examples/blob/master/src/cubemap/CMakeLists.txt) seems to install them into a possibly different folder than the binary?

**Comment by mosra** [comment]
@acterhd when installing, the images are put into a different folder than the binary in order to follow Unix filesystem standards (no jpegs should ever be present in `/usr/bin` and no binaries should be present in `/usr/share`). As the README says, the app has one optional command-line parameter with which you can specify path to the image files, so either the following, if you run the binary from your build dir:

```sh
./magnum-cubemap ~/magnum-examples/src/cubemap/
```

Or if you installed to `/usr`:

```sh
/usr/bin/magnum-cubemap /usr/share/magnum/examples/cubemap/
```

The same could also be done by just changing the PWD to where the images are:

```sh
cd ~/magnum-examples/src/cubemap/
~/magnum-examples/build/src/cubemap/magnum-cubemap
```

**Comment by mosra** [comment]
Closing as resolved.
