### ISSUE TITLE
Rendering issues with firefox 

### ISSUE THREAD

**Issue by Lectem** [mosra/magnum-examples#34]
I am not sure if this is an issue with magnum itself or with firefox (perhaps webgl2 only?), but the model viewer seems to have some depth issues. It does not happen with Edge on the same computer.

 Here are the webgl reports:

# Firefox

![image](https://user-images.githubusercontent.com/6024225/29995388-6be3d452-8fe8-11e7-9a57-be66c43e140b.png)

## Webgl 1

Platform: | Win32
-- | --
Browser   User Agent: | Mozilla/5.0 (Windows NT 10.0;   WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
Context   Name: | webgl
GL   Version: | WebGL 1.0
Shading   Language Version: | WebGL GLSL ES 1.0
Vendor: | Mozilla
Renderer: | Mozilla
Unmasked   Vendor: | Google Inc.
Unmasked   Renderer: | ANGLE (Intel(R) HD Graphics 4600   Direct3D11 vs_5_0 ps_5_0)
Antialiasing: | Available
ANGLE: | Yes, D3D11
Major   Performance Caveat: | No

## Webgl 2

Platform: | Win32
-- | --
Browser   User Agent: | Mozilla/5.0 (Windows NT 10.0;   WOW64; rv:55.0) Gecko/20100101 Firefox/55.0
Context   Name: | webgl2
GL   Version: | WebGL 2.0
Shading   Language Version: | WebGL GLSL ES 3.00
Vendor: | Mozilla
Renderer: | Mozilla
Unmasked   Vendor: | Google Inc.
Unmasked   Renderer: | ANGLE (Intel(R) HD Graphics 4600   Direct3D11 vs_5_0 ps_5_0)
Antialiasing: | Available
ANGLE: | Yes, D3D11
Major   Performance Caveat: | No

# Edge

![image](https://user-images.githubusercontent.com/6024225/29995395-80742624-8fe8-11e7-8c87-3423c66cc6d1.png)

Platform: | Win32
-- | --
Browser   User Agent: | Mozilla/5.0 (Windows NT 10.0;   Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116   Safari/537.36 Edge/15.15063
Context   Name: | experimental-webgl
GL   Version: | WebGL 1.0
Shading   Language Version: | WebGL GLSL ES 1.0
Vendor: | Microsoft
Renderer: | Microsoft Edge
Unmasked   Vendor: | Microsoft
Unmasked   Renderer: | Intel(R) HD Graphics 4600
Antialiasing: | Available
ANGLE: | No
Major   Performance Caveat: | No

No webgl2 support

**Comment by Lectem** [comment]
Just saw that the depth buffer had only 16bits precisions for firefox, this could be the reason for this issue... Full report here : 
# Firefox 
![image](https://user-images.githubusercontent.com/6024225/29995603-b0395992-8fed-11e7-9783-8558207401dd.png)


# Edge 
![image](https://user-images.githubusercontent.com/6024225/29995601-9df6ef7e-8fed-11e7-908b-938c53a5f607.png)

**Comment by mosra** [comment]
Fixed in f579befe2a50d93e7b4f2ecf12cc349faff6f13b, thanks for all the help on Gitter. 

Just for the record: was a depth buffer issue, 16bit not being enough for the crazy depth range in the projection matrix, reducing that range made it work.
