### ISSUE TITLE
Issue with http://magnum.graphics/showcase/picking/

### ISSUE THREAD

**Issue by trsh** [mosra/magnum-examples#37]
EmscriptenApplication.js:15 exception thrown: TypeError: Cannot read property 'getParameter' of undefined,TypeError: Cannot read property 'getParameter' of undefined
    at _glGetString (http://static.magnum.graphics/showcase/picking/magnum-picking.js:1:187188)
    at wasm-function[296]:160
    at wasm-function[159]:688
    at wasm-function[169]:52
    at Object.Module._main (http://static.magnum.graphics/showcase/picking/magnum-picking.js:1:231714)
    at Object.callMain (http://static.magnum.graphics/showcase/picking/magnum-picking.js:1:239067)
    at doRun (http://static.magnum.graphics/showcase/picking/magnum-picking.js:1:239810)
    at http://static.magnum.graphics/showcase/picking/magnum-picking.js:1:239960
printErr @ EmscriptenApplication.js:15
callMain @ magnum-picking.js:1
doRun @ magnum-picking.js:1
(anonymous) @ magnum-picking.js:1
setTimeout (async)
run @ magnum-picking.js:1
runCaller @ magnum-picking.js:1
removeRunDependency @ magnum-picking.js:1
receiveInstance @ magnum-picking.js:1
receiveInstantiatedSource @ magnum-picking.js:1
Promise.then (async)
doNativeWasm @ magnum-picking.js:1
Module.asm @ magnum-picking.js:1
(anonymous) @ magnum-picking.js:1
magnum-picking.js:1 Uncaught TypeError: Cannot read property 'getParameter' of undefined
    at _glGetString (magnum-picking.js:1)
    at /showcase/picking/wasm-function[296]:160
    at /showcase/picking/wasm-function[159]:688
    at /showcase/picking/wasm-function[169]:52
    at Object.Module._main (magnum-picking.js:1)
    at Object.callMain (magnum-picking.js:1)
    at doRun (magnum-picking.js:1)
    at magnum-picking.js:1

**Comment by mosra** [comment]
Hi!

Can you tell me which browser, OS and GPU is this error happening on? Is there anything printed in the console before this error? Does [magnum-info](http://magnum.graphics/showcase/magnum-info/) work? And the [WebGL 2 version of magnum-info](http://magnum.graphics/showcase/magnum-info-webgl2/)?

**Comment by trsh** [comment]
Only this error.  Win 10. GeForce 6150SE nForce 430

magnum-info

```
  +---------------------------------------------------------+
  | Information about Magnum engine and OpenGL capabilities |
  +---------------------------------------------------------+

Used application: Platform::WindowlessEglApplication
Compilation flags:
    CORRADE_BUILD_DEPRECATED
    CORRADE_BUILD_STATIC
    CORRADE_TARGET_EMSCRIPTEN
    MAGNUM_BUILD_DEPRECATED
    MAGNUM_BUILD_STATIC
    MAGNUM_BUILD_MULTITHREADED
    MAGNUM_TARGET_GLES
    MAGNUM_TARGET_GLES2
    MAGNUM_TARGET_WEBGL

Renderer: WebKit WebGL by WebKit
OpenGL version: OpenGL ES 2.0 (WebGL 1.0 (OpenGL ES 2.0 Chromium))
Using optional features:
    GL_ANGLE_instanced_arrays
    GL_EXT_texture_filter_anisotropic
    GL_OES_vertex_array_object
Detected driver: Context::DetectedDriver::Angle
Supported GLSL versions:
    OpenGL ES GLSL ES 1.00 (WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium))

WebGL 2.0 extension support:
    GL_ANGLE_instanced_arrays                                     SUPPORTED
    GL_EXT_sRGB                                                       -
    GL_EXT_blend_minmax                                           SUPPORTED
    GL_EXT_shader_texture_lod                                     SUPPORTED
    GL_OES_texture_float                                          SUPPORTED
    GL_OES_texture_half_float                                     SUPPORTED
    GL_OES_standard_derivatives                                   SUPPORTED
    GL_OES_vertex_array_object                                    SUPPORTED
    GL_OES_element_index_uint                                     SUPPORTED
    GL_OES_texture_float_linear                                       -
    GL_OES_texture_half_float_linear                                  -
    GL_OES_fbo_render_mipmap                                          -
    GL_WEBGL_depth_texture                                            -
    GL_WEBGL_draw_buffers                                             -

Vendor extension support:
    GL_EXT_texture_filter_anisotropic                             SUPPORTED
    GL_EXT_disjoint_timer_query                                       -
    GL_WEBGL_compressed_texture_s3tc                              SUPPORTED
```

**Comment by trsh** [comment]
WebGL 2 info

```
 +---------------------------------------------------------+
  | Information about Magnum engine and OpenGL capabilities |
  +---------------------------------------------------------+

Used application: Platform::WindowlessEglApplication
Compilation flags:
    CORRADE_BUILD_DEPRECATED
    CORRADE_BUILD_STATIC
    CORRADE_TARGET_EMSCRIPTEN
    MAGNUM_BUILD_DEPRECATED
    MAGNUM_BUILD_STATIC
    MAGNUM_BUILD_MULTITHREADED
    MAGNUM_TARGET_GLES
    MAGNUM_TARGET_WEBGL

Could not create canvas: Failed to create a WebGL2 context.,:(,{"antialias":true,"alpha":false,"depth":true,"stencil":true,"majorVersion":2,"minorVersion":0}
Platform::WindowlessEglApplication::tryCreateContext(): cannot create EGL context: EGL_BAD_MATCH
```

**Comment by trsh** [comment]
Btw it's same with > http://magnum.graphics/showcase/magnum-ui-gallery/

**Comment by mosra** [comment]
Hmm. It seems that your card simply doesn't support WebGL 2 (or Chrome blacklists WebGL 2 on it, not sure) and so every example that requires WebGL 2 fails to load. Looking at it, the card is from 2005, so I would say this is expected :)

Native versions of these examples could maybe work, but even there I'm not sure.

**Comment by trsh** [comment]
Mkay. So you are slowly going on WebGL 2 only?

**Comment by mosra** [comment]
I'm trying not to, but some things require features present only on WebGL 2 and can't be backported to WebGL 1:

- the [Picking example](http://magnum.graphics/showcase/picking/) uses multiple fragment outputs and an integer texture to record what object ID is being clicked on, no chance to get that on WebGL 1
- the UI used in the [UI gallery](http://magnum.graphics/showcase/magnum-ui-gallery/) and the [Area Lights example](http://magnum.graphics/showcase/picking/) is designed around uniform buffers, not possible with WebGL 1

That's all so far. Dropping WebGL 1 and OpenGL ES 2 would save me quite a lot of backporting effort, but there's still a lot of platforms where this isn't possible (as far as I know, neither macOS nor iOS have any support for WebGL 2 yet), > 30% of Android devices still don't support ES3 etc. So nothing to worry about for the next few years at least :)

**Comment by trsh** [comment]
@mosra it's fine in not running some NEW, fancy stuff, but an UI, I think, should totally run in WEBGL 1. For the same reasons you are pointing out :P

**Comment by mosra** [comment]
I may consider that later when I get to doing UI stuff again, yes. The UI lib is currently in an experimental state so I think this is forgivable at the moment ;)

**Comment by trsh** [comment]
Okay. Closing this.
