### ISSUE TITLE
vcpkg build: SDL2.dll dependency is not automatically copied

### ISSUE THREAD

**Issue by Squareys** [mosra/magnum-examples#42]
From https://github.com/mosra/magnum-examples/issues/41#issuecomment-386381318.

When building with vcpkg (e.g. x64-windows triplet), you can usually just run the application and it "just works", because all the dependency DLLs are automatically copied to the target output folder.

This works well for all dynamic libraries (e.g. `MagnumPlugins::FreetypeFont`), but not for Sdl2Application, which is always linked statically.
Since the executable is a dynamic library itself, I would expect it to work anyway, but that is maybe not how vcpkg works.

@mosra You may assign me, I will have a look at this in near future.

**Comment by Squareys** [comment]
Yeah, would be nice for me, too 😜 I'm still not 100% sure why this even is an issue. It's definitely possible, though, I guess.... (at worst with some .ps script 😅 )

**Comment by Squareys** [comment]
New lead: This works just fine with `Release` configuration, only fails with `Debug`.

**Comment by Squareys** [comment]
So, I think what's happening is the following:

 - there is `windows-x64/bin/SDL2.dll` and `windows-x64/debug/bin/SDL2d.dll`
 - if I launch the Debug build of triangle-example, it complains about SDL2~~d~~.dll missing! Which means it must be linking agains the non-debug version.
 - vcpkg now tries to copy over SDL2.dll from `windows-x64/debug/bin/`, and fails, because that's in  `windows-x64/~~debug/~~bin/`

Hence, the fix is to link against the right lib? Maybe by adapting the find package so that it finds `SDL2d.lib`, it currently only finds `SDL2.lib`.

**Comment by mosra** [comment]
Ahh. So the culprit is in FindSDL.cmake, right? Would you be able to convince it to handle both debug and release build properly? Thanks! :+1:

**Comment by Squareys** [comment]
(For others, I fixed the FindModule, but am still in the process of testing this with SDL prebuilt binaries, but my compiler setup gave up on me, so the pullrequest is being delayed a bit by having to fix that)

**Comment by mosra** [comment]
Solved with #45, merged into mosra/magnum@52b7c26022b2e5133f84b616a4d22e9e50e90a90 and then copied into all other repos.

**Comment by Squareys** [comment]
Wow, I shot myself in the foot here 💥 🔫 

I thought `vcpkg install --head magnum` now fails because it couldn't find SDL2 and panically tried to figure out why at 6 AM... but I had manually removed release SDL to test the find module for the pullrequest 😅 Took me a while to figure out, though.

Works great now!

I noticed a thing, though: https://github.com/mosra/magnum/blob/master/modules/FindSDL2.cmake#L65 should probably be `SDL2_LIBRARY_RELEASE` or be moved after line 70. (sorry! 🙈)

**Comment by mosra** [comment]
> I noticed a thing

Spotted that too, but this shouldn't be a problem. FPHSA just needs one of the LIBRARY variables to check that SDL was found (so either of them) and the var dereferencing is not done until much later below. Should be explained in a comment, though. I'll add that.
