### ISSUE TITLE
Cannot compile examples with apt package

### ISSUE THREAD

**Issue by RaulPPelaez** [mosra/magnum-examples#47]
Following the guide I tried to compile TriangleExample.cpp. But I get these errors:
```bash
magnum-examples/src/triangle/TriangleExample.cpp:65:24: error: no matching function for call to ‘Magnum::GL::Buffer::setData(const Magnum::Examples::TriangleExample::TriangleExample(const Magnum::Platform::Sdl2Application::Arguments&)::TriangleVertex [3])’
     buffer.setData(data);

magnum-examples/src/triangle/TriangleExample.cpp:70:13: error: ‘Color3’ is not a member of ‘Magnum::Shaders::VertexColor2D {aka Magnum::Shaders::VertexColor<2u>}’
             Shaders::VertexColor2D::Color3{});

```

Maybe it is a version mismatch problem, but I dont see in the docs any mention to these changes.

BTW magnum-examples-dev package is not present in the Ubuntu package (I am trying to run it in Ubuntu 18.04)

**Comment by mosra** [comment]
Hi! :)

The `master` branch of the examples depends on `master` branch of magnum, this particular error is related to [this feature](http://doc.magnum.graphics/magnum/changelog.html#changelog-latest-changes-shaders) that's not available in any stable version yet. Depending on what apt package you used (I *think* the stable 2018.04 version from the PPA?), you might want to do one of these things:

- keep using the stable 2018.04 version and check out the `v2018.04` tag of examples to have code that's compatible with it
- or build your own `*.deb` packages from the `master` branch. It's just two commands, but note you need to do that for all projects (corrade, magnum, magnum-plugins, ...). Detailed guide is [in the docs](http://doc.magnum.graphics/magnum/building.html#building-packages-deb).

**Comment by RaulPPelaez** [comment]
Thanks for the instant answer!
Yes, the version is 2018.04.
I checkout'ed the v2018.04 branch in the examples repo and it now compiles without issue as you predicted. 
Thanks again!
