### ISSUE TITLE
typo, should be jpge-importer

### ISSUE THREAD

**Issue by hunt978** [mosra/magnum-examples#54]
https://github.com/mosra/magnum-examples/blob/1b47e6f52c56cb55b41bb4b8846bfbf6ce7f038e/src/cubemap/CubeMapExample.cpp#L80

**Comment by mosra** [comment]
![image](https://user-images.githubusercontent.com/344828/52865347-ba01f500-313c-11e9-870b-cf411b9fdfaf.png)

Thanks! Fixed in 267d3bbf1a04938c1d77d537fa74a92417888032.
