### ISSUE TITLE
Area light example, area quads don't use depth buffer

### ISSUE THREAD

**Issue by haxiomic** [mosra/magnum-examples#57]
Love the demo btw :)

Just spotted lights don't occlude each other correctly (yellow is the closest in this screenshot)

<img width="637" alt="screenshot 2019-03-04 at 16 51 31" src="https://user-images.githubusercontent.com/3742992/53748751-e4261780-3e9d-11e9-8188-6736aff75348.png">

**Comment by mosra** [comment]
Hi, thanks! Should be fixed in cbbaa48cd454337298fb15b91789112efe23f0df, the web version is now updated as well (and it turns out to be ~100 kB smaller than before, not sure if due to optimizations in Emscripten or in Magnum itself).

**Comment by haxiomic** [comment]
Nice one :)
