### ISSUE TITLE
Build failure on Ubuntu

### ISSUE THREAD

**Issue by hzyjerry** [mosra/magnum-examples#61]
I tried building the examples and get the following error:

```Scanning dependencies of target magnum-viewer
[ 50%] Building CXX object CMakeFiles/magnum-viewer.dir/ViewerExample.cpp.o
/home/jerry/Desktop/Projects/habitat/magnum-examples/src/viewer/ViewerExample.cpp:34:38: fatal error: Corrade/Utility/DebugStl.h: No such file or directory
compilation terminated.
CMakeFiles/magnum-viewer.dir/build.make:62: recipe for target 'CMakeFiles/magnum-viewer.dir/ViewerExample.cpp.o' failed
make[2]: *** [CMakeFiles/magnum-viewer.dir/ViewerExample.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/magnum-viewer.dir/all' failed
make[1]: *** [CMakeFiles/magnum-viewer.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

I have corrade installed using `sudo ap-get install corrade corrade-dev`.

**Comment by mosra** [comment]
Hi, sorry about that -- the PPA you most probably installed from is heavily outdated and not maintained anymore by the original contributor. To avoid further confusion, I removed all mentions of it from the documentation (see mosra/magnum@a6df7493bbaf8a05feddf22ef1980c8612c9dbfa) -- the recommeded way is to [build the packages manually instead](https://doc.magnum.graphics/magnum/building.html#building-packages-deb).

If you have `master` of all repos, things should work correctly -- everything gets checked daily on the CIs, see the [Build Status](https://magnum.graphics/build-status/) page.
