### ISSUE TITLE
Undefined variabls

### ISSUE THREAD

**Issue by janbajana** [mosra/magnum-examples#66]
Hello guys, 

after the last update to magnum "master" I got compilation errors If I build examples.
Did something change for magnum linking? This came after last pull. There is a ton of undefined types. Or I did something wrong?

example of the error:
`e:\git\magnum-examples\src\shadows\shadowsexample.cpp(290): error C2027: use of undefined type 'Magnum::Math::Color3<Magnum::Float>'`

My build script (tested Windows build):
https://github.com/janbajana/script-helpers/blob/master/cmake-scripts/setup-magnum-examples-build.sh

**Comment by mosra** [comment]
Hi, sorry, this is because I pushed a header-hygiene commit to Magnum late last week (https://github.com/mosra/magnum/commit/a0f0015211920b32ff30c6f7e2e2ed77b04a155f) but didn't have time to update the depending projects for it yet. I'm on that today, will ping you once it's done :)

**Comment by janbajana** [comment]
Super. Thank you for the quick update.

**Comment by mosra** [comment]
With 76d2afa2790daca0788c2b7f69e3d29699c6709f (and also mosra/magnum-integration@4431f9b93dd3ebdd0548b2beb5cc8ec0df863834 and mosra/magnum-bindings@106ca8f3142fe118903bf8c8fc48b7c96f6831b6), using `master` of everything should work again.

Just a note -- I'm doing a bunch of buildsystem-related changes to the repos in preparation for a stable release, so a few more similar issues might temporarily pop up over the next few days, until it settles down again -- such breakages are quite uncommon for this project.
