### ISSUE TITLE
Fix HDPI problem for WebGL examples

### ISSUE THREAD

**Issue by ttnghia** [mosra/magnum-examples#74]
Hi there,

I create this issue to make sure we don't forget about our high-DPI problem: mouse position is not correct when running WebGL examples on high DPI monitor.

The examples still have this problem: Bullet and Fluid2D (please add more if you know).

**Comment by mosra** [comment]
Fixed in 5d76174180ea4cbedc1b882b996eafa88b043e3d 🎉 

Sorry it took so long.
