### ISSUE TITLE
Creating my own glb

### ISSUE THREAD

**Issue by Korotsu** [mosra/magnum-examples#77]
Hello,
I'm trying to change the model from the viewer example but I couldn't find a way to create my own glb file with blender... The glb file I exported from blender is not working, the error is:
`
Opening file ../../magnum-examples/src/viewer/out.glb
Trade::AbstractImporter::openFile(): cannot open file ../../magnum-examples/src/viewer/out.glb
`

I tried re building the example with the following line modified in the CMakeLists.txt: 
`
install(FILES out.glb DESTINATION ${MAGNUM_DATA_INSTALL_DIR}/examples/viewer)
`
In the magnum installation's plugins I checked:
`
-DWITH_ASSIMPIMPORTER=ON \
-DWITH_DDSIMPORTER=ON \
-DWITH_STBIMAGEIMPORTER=ON \
-DWITH_STBTRUETYPEFONT=ON \
-DWITH_TINYGLTFIMPORTER=ON
`

Am I doing something wrong ?

**Comment by mosra** [comment]
Hi! Sorry for the late reply, getting too many notification lately and only slowly catching up. 

This error in 99% cases means it couldn't find the file, the remaining 1% is if the file can't be read (permission issue and such, not very common). Can you try with an absolute path instead (which you're sure exists)? That should work.

**Comment by mosra** [comment]
Closed for lack of activity.
