### ISSUE TITLE
EmscriptenApplication.js:35:2:WebXR unsupported in this browser

### ISSUE THREAD

**Issue by yylittlefish** [mosra/magnum-examples#87]
Hi, 
I build webxr for emscripten in ubuntu, and generated :
EmscriptenApplication.js
magnum-webxr.html
 magnum-webxr.js
magnum-webxr.wasm
WebApplication.css

I setup a server using python SimpleHTTPServer and access the html with my PC browser,
I could see a image in the browser but there's error log in console:WebXR unsupported in this browser

I tried it in chromium and Edge, they have the same issue.
my Chromium version is  83.0.4103.116（正式版本） （32 位）

Have anybody met this kind of issue? any help will be appreciated!

**Comment by mosra** [comment]
Pinging @Squareys, since he's the WebXR guru here :)

**Comment by Squareys** [comment]
Hey @yylittlefish ,

Desktop Chromium don't support WebXR yet, I think. You could try Firefox with HTC Vive, but apart from that, you're still out of luck. It should definitely work on the Oculus Browser, though, in case you have an Oculus Quest or Oculus GO.

**Comment by yylittlefish** [comment]
> Hey @yylittlefish ,
> 
> Desktop Chromium don't support WebXR yet, I think. You could try Firefox with HTC Vive, but apart from that, you're still out of luck. It should definitely work on the Oculus Browser, though, in case you have an Oculus Quest or Oculus GO.

Hi, thank you for your reply!

"Desktop Chromium don't support WebXR yet" => does any other version Chromium support WebXR?
actually I finally want to run the webXR example in TV, it contains chromium browser too.

I installed firefox browser with version 78.0.1, but not connected with HTC Vive, it also shows "WebXR unsupported in this browser"
does the WebXR feature only supported when VR/XR devices are connected?
library_webxr.js calls w3c webxr apis in this page: https://www.w3.org/TR/webxr/#xr-device-concept
even if there's no HTC Vive, the APIs should be supported, right?(in both chromium and firefox).

**Comment by mosra** [comment]
Vaguely related, the WebXR demo is now also available on https://magnum.graphics/showcase/webxr/
