### ISSUE TITLE
<box2d/box2d.h> case-sensitive issue

### ISSUE THREAD

**Issue by pixelblender** [mosra/magnum-examples#92]
Currently `Box2DExample.cpp` uses `#include <Box2D/Box2D.h>` while the actual box2d repo uses lower-case. This cause issue with case-sensitive filesystem on Linux. Change the include to use `#include <box2d/box2d.h>` fixes it.

**Comment by mosra** [comment]
Hi, yes, that's what #90 aims to fix ... and I'm to blame here for taking ages to merge, sorry about that.

Some background -- the example was originally made against version 2.3, which was from 2014 or so and there the headers actually were CamelCase. Only very recently 2.4 got released, which basically renamed everything.

**Comment by pixelblender** [comment]
Sorry I missed #90 didn't see that one. Thanks for this awesome library and keep up the good work! :+1:
